import type { Metadata } from "next";
import StyledComponentsRegistry from "@/lib/registry";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import TabsBar from "@/components/TabsBar";
import AppWrapper from "@/components/AppWrapper";
import SearchInput from "@/components/SearchInput";
import { ContentWrapper, Title, Subtitle } from "./styles";
import { SearchProvider } from "@/context/SearchContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({
  children,
}: Readonly<{
  children?: React.ReactNode;
}>) => {
  return (
    <StyledComponentsRegistry>
      <SearchProvider>
        <AppWrapper>
          <ContentWrapper>
            <Header />
            <Title>The places you dream of</Title>
            <Subtitle>Let&apos;s live new adventures</Subtitle>
            <SearchInput />
            <TabsBar />
            {children}
          </ContentWrapper>
        </AppWrapper>
      </SearchProvider>
      <Footer />
    </StyledComponentsRegistry>
  );
};
export default Layout;
