import type { Metadata } from "next";
import StyledComponentsRegistry from "../lib/registry";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import TabsBar from "@/components/TabsBar";
import AppWrapper from "@/components/AppWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body>
          <AppWrapper>
            <Header />
            {children}
            <TabsBar />
            <Footer />
          </AppWrapper>
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
